{{- if or .Values.azure.sourceSubscriptionId .Values.azure.destinationSubscriptionId (eq .Values.authentication.method "service-principal") .Values.notifications.slack.enabled .Values.notifications.teams.enabled .Values.notifications.telegram.enabled .Values.notifications.email.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "akv-sync.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "akv-sync.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.azure.sourceSubscriptionId }}
  SOURCE_SUBSCRIPTION_ID: {{ .Values.azure.sourceSubscriptionId | quote }}
  {{- end }}
  {{- if .Values.azure.destinationSubscriptionId }}
  DESTINATION_SUBSCRIPTION_ID: {{ .Values.azure.destinationSubscriptionId | quote }}
  {{- end }}

  {{- if eq .Values.authentication.method "service-principal" }}
  {{- if .Values.authentication.servicePrincipal.clientId }}
  SERVICE_PRINCIPAL_ID: {{ .Values.authentication.servicePrincipal.clientId | quote }}
  {{- end }}
  {{- if .Values.authentication.servicePrincipal.tenantId }}
  SERVICE_PRINCIPAL_TENANT_ID: {{ .Values.authentication.servicePrincipal.tenantId | quote }}
  {{- end }}
  {{- if .Values.authentication.servicePrincipal.clientSecret }}
  SERVICE_PRINCIPAL_SECRET: {{ .Values.authentication.servicePrincipal.clientSecret | quote }}
  {{- end }}
  {{- end }}

  {{- if .Values.notifications.email.enabled }}
  {{- if .Values.notifications.email.smtpUser }}
  SMTP_USER: {{ .Values.notifications.email.smtpUser | quote }}
  {{- end }}
  {{- if .Values.notifications.email.smtpPassword }}
  SMTP_PASSWORD: {{ .Values.notifications.email.smtpPassword | quote }}
  {{- end }}
  {{- end }}

  {{- if and .Values.notifications.slack.enabled .Values.notifications.slack.webhookUrl }}
  SLACK_WEBHOOK_URL: {{ .Values.notifications.slack.webhookUrl | quote }}
  {{- end }}

  {{- if and .Values.notifications.teams.enabled .Values.notifications.teams.webhookUrl }}
  TEAMS_WEBHOOK_URL: {{ .Values.notifications.teams.webhookUrl | quote }}
  {{- end }}

  {{- if .Values.notifications.telegram.enabled }}
  {{- if .Values.notifications.telegram.botToken }}
  TELEGRAM_BOT_TOKEN: {{ .Values.notifications.telegram.botToken | quote }}
  {{- end }}
  {{- if .Values.notifications.telegram.chatId }}
  TELEGRAM_CHAT_ID: {{ .Values.notifications.telegram.chatId | quote }}
  {{- end }}
  {{- end }}
{{- end }}
