{{ if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "akv-sync.labels" . | nindent 4 }}
    {{- with .Values.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if and (eq .Values.authentication.method "workload-identity") .Values.azureIdentity.enabled }}
    azure.workload.identity/client-id: {{ .Values.azureIdentity.clientId | quote }}
    azure.workload.identity/tenant-id: {{ .Values.azureIdentity.tenantId | quote }}
    {{- end }}
{{- end }}